services:
  db:
    extends:
      file: db/docker-compose.yml
      service: db
    networks:
      backend:

  flyway:
    extends:
      file: flyway/docker-compose.yml
      service: flyway
    networks:
      backend:
    depends_on:
      db:
        condition: service_healthy

  backend:
    extends:
      file: backend/docker-compose.yml
      service: backend
    networks:
      backend:
      prodenv-shared-internal:
        aliases:
          - ${COMPOSE_PROJECT_NAME}-backend
      artist-insight-shared:
        aliases:
          - ${COMPOSE_PROJECT_NAME}-backend
    depends_on:
      flyway:
        condition: service_completed_successfully

  chat-collector:
    extends:
      file: chat-collector/docker-compose.yml
      service: chat-collector
    networks:
      backend:
    depends_on:
      backend:
        condition: service_healthy

  frontend:
    extends:
      file: frontend/docker-compose.yml
      service: frontend
    networks:
      prodenv-shared-internal:
        aliases:
          - ${COMPOSE_PROJECT_NAME}-frontend
    depends_on:
      backend:
        condition: service_healthy

volumes:
  volume-db:
  volume-db-backup:

networks:
  backend:
  # TODO: rename that network
  prodenv-shared-internal:
    external: true
  artist-insight-shared:
    external: true