services:
  backend:
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:9561:9561
  db:
    ports:
      - 127.0.0.1:5432:5432
  frontend:
    ports:
      - 127.0.0.1:3000:3000

  chat-stubs:
    extends:
      file: chat-stubs/docker-compose.yml
      service: chat-stubs
    networks:
      backend:

  chat-collector:
    depends_on:
      chat-stubs:
        condition: service_started
