services:
  sinair-llm-bot-prod:
    environment:
      APP_ENVIRONMENT: prod
    cpus: "${BACKEND_CPU_LIMIT:-1.00}"
    mem_limit: ${BACKEND_MEMORY_LIMIT:-768m}
    memswap_limit: ${BACKEND_MEMORY_SWAP_LIMIT:-1024m}

  sinair-llm-bot-stage:
    cpus: "${BACKEND_CPU_LIMIT:-0.50}"
    mem_limit: ${BACKEND_MEMORY_LIMIT:-512m}
    memswap_limit: ${BACKEND_MEMORY_SWAP_LIMIT:-768m}