package org.taonity.sinairllmbot.console.entity

enum class AuditAction {
    DELETE_CHAT_MESSAGE,
    DELETE_CHAT_EVENT,
    DELETE_OUTBOUND_MESSAGE,
    DELETE_PIPELINE_RUN,
    EDIT_SUMMARY,
    DELETE_SUMMARY,
    REQUEST_ACCESS,
    APPROVE_ACCESS,
    REJECT_ACCESS,
    CHANGE_ROLE,
    EDIT_CONFIG,
    RESET_CONFIG,
    ADD_TIER,
    DELETE_TIER,
}
