name: local
variables:
  - name: frontendUrl
    value: http://localhost:3000
  - secret: true
    name: cookies
  - secret: true
    name: xsrfToken
  - secret: true
    name: cookies
  - secret: true
    name: xsrfToken
  - secret: true
    name: cookies
  - secret: true
    name: xsrfToken
