spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:file:./h2_db
    username: sa
    password: sa
        url: jdbc:h2:file:./h2_db

  flyway:
    enabled: true
    clean-disabled: false
    locations:
      - filesystem:templates/docker/flyway/sql/tables
      - filesystem:templates/docker/flyway/sql/conflicts/h2

  sql:
    init:
      mode: always

app:
  additional-profiles: flyway-clean-migrate
