spring:
  security:
    oauth2:
      client:
        registration:
          google-sinair-llm-bot:
            provider: google
            client-id: stub-google-client-id
            client-secret: stub-google-client-secret
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/google-sinair-llm-bot
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          google:
            authorization-uri: http://127.0.0.1:9561/oauth2/authorize
            token-uri: http://127.0.0.1:9561/oauth2/token
            user-info-uri: http://127.0.0.1:9561/oauth2/v3/userinfo

app:
  default-success-url: http://127.0.0.1:3000
  login-url: http://127.0.0.1:3000

logging:
  level:
    WireMock: warn
